// AR/VR expansion (add to questions.js after Blockchain section)
const AR_VR_QUESTIONS = {
  "AR/VR & Mixed Reality": {
    "easy": [
      { id: "ar_e1", question: "What is the key difference between Augmented Reality (AR) and Virtual Reality (VR)?", options: ["AR replaces reality; VR overlays digital elements on reality", "AR overlays digital content onto the real world; VR creates a fully synthetic environment", "AR requires high-end motion suits; VR requires mobile phone cameras", "They are identical technologies"], answer: 1, explanation: "AR enhances the physical environment, while VR replaces it with immersive synthetic graphics." },
      { id: "ar_e2", question: "What does 6DoF stand for in spatial motion tracking?", options: ["6 Degrees of Freedom", "6 Directions of Forwarding", "6 Digital Optical Filters", "6 Dimensions of Frame-rate"], answer: 0, explanation: "6DoF tracking captures translational (X,Y,Z) and rotational (Pitch, Yaw, Roll) movements." },
      { id: "ar_e3", question: "Which game engine is widely used for building cross-platform AR/VR experiences?", options: ["Unity", "Excel", "Photoshop", "Docker"], answer: 0, explanation: "Unity is a standard engine for real-time 3D spatial development." },
      { id: "ar_e4", question: "What is 'presence' in VR terminology?", options: ["Physical attendance", "Psychological sensation of being immersed in a virtual environment", "Avatar appearance", "Network connectivity"], answer: 1, explanation: "Presence is the feeling of 'being there' in a virtual space." },
      { id: "ar_e5", question: "What does 'immersion' mean in XR contexts?", options: ["Water submersion", "Degree of sensory engagement replacing real-world perception", "Video quality", "Audio volume"], answer: 1, explanation: "Immersion measures how fully users feel present in synthetic environments." },
      { id: "ar_e6", question: "What is 'Mixed Reality (MR)'?", options: ["Same as VR", "Blending virtual and real world elements interacting in real-time", "Only AR", "Gaming only"], answer: 1, explanation: "MR merges digital objects with physical space enabling interaction." },
      { id: "ar_e7", question: "What does 'tracking' accomplish in AR/VR?", options: ["Recording user actions", "Monitoring user position and orientation for rendering correctness", "Surveillance only", "Network bandwidth"], answer: 1, explanation: "Tracking ensures virtual content aligns with user perspective and movement." }
    ],
    "medium": [
      { id: "ar_m1", question: "What is spatial anchor technology in AR frameworks like ARKit/ARCore?", options: ["A physical weight attached to headgear", "A persistent digital coordinate point mapped to physical environment features", "An anchor tag in HTML web pages", "A battery charging interface"], answer: 1, explanation: "Spatial anchors lock virtual objects to precise physical locations across sessions." },
      { id: "ar_m2", question: "What physical symptom does high motion-to-photon latency cause in VR users?", options: ["Color blindness", "Motion sickness / Vergence-Accommodation Conflict", "Reduced audio hearing", "Hardware overheating"], answer: 1, explanation: "Lag between head motion and visual update causes sensory mismatch and motion sickness." },
      { id: "ar_m3", question: "What is Passthrough technology in modern VR headsets?", options: ["Passing audio through Bluetooth", "Using external cameras to view physical surroundings inside the VR display", "Bypassing password screens", "Streaming gameplay to external TVs"], answer: 1, explanation: "Passthrough streams camera video feeds real-time into display optics for Mixed Reality." },
      { id: "ar_m4", question: "What is 'hand tracking' in VR systems?", options: ["Following user movement only", "Recognizing and tracking hand gestures enabling direct manipulation without controllers", "Wrist fitness tracking", "Database indexing"], answer: 1, explanation: "Hand tracking enables natural gesture-based interaction without physical controllers." },
      { id: "ar_m5", question: "What is 'eye tracking' used for in VR?", options: ["Screen brightness only", "Determining gaze direction for foveated rendering and gaze-based interaction", "Video recording", "Network monitoring"], answer: 1, explanation: "Eye tracking enables gaze-based interaction and performance optimization." },
      { id: "ar_m6", question: "What does 'haptic feedback' provide in XR?", options: ["Visual signals", "Tactile sensations via vibration/force feedback simulating physical touch", "Audio cues", "Temperature control"], answer: 1, explanation: "Haptics enable users to 'feel' virtual interactions enhancing immersion." },
      { id: "ar_m7", question: "What is 'volumetric capture' in XR content creation?", options: ["Recording speaker volume", "Capturing full 3D geometry and appearance of real objects/people", "Text storage", "Compression technique"], answer: 1, explanation: "Volumetric capture creates realistic 3D representations of real-world subjects." }
    ],
    "hard": [
      { id: "ar_h1", question: "What is Foveated Rendering in modern spatial computing?", options: ["Rendering frames in grayscale", "Concentrating high graphical detail exclusively where the eye pupil is gazing using eye tracking", "Lowering overall screen resolution", "Rendering 3D scenes without shadows"], answer: 1, explanation: "Foveated rendering lowers GPU load by lowering quality in peripheral vision." },
      { id: "ar_h2", question: "What causes the Vergence-Accommodation Conflict (VAC) in stereoscopic displays?", options: ["Low battery power", "Eyes converging at one distance while focal lenses accommodate at a fixed screen plane distance", "Mismatched audio channels", "Reflective optical glares"], answer: 1, explanation: "VAC occurs when synthetic visual distance mismatch causes eye fatigue." },
      { id: "ar_h3", question: "Which open cross-platform standard simplifies XR application development across vendor headsets?", options: ["OpenXR", "WebGL", "DirectX 11", "Vulkan GL"], answer: 0, explanation: "OpenXR provides an open API standard connecting XR application code to diverse hardware." },
      { id: "ar_h4", question: "What is 'light field rendering' in advanced AR/VR?", options: ["Basic 3D rendering", "Capturing complete light ray information for photorealistic image synthesis from any viewpoint", "Lighting simulation only", "Screen brightness"], answer: 1, explanation: "Light field rendering achieves unprecedented visual realism through full angular information." },
      { id: "ar_h5", question: "What is 'SLAM' (Simultaneous Localization and Mapping) in AR?", options: ["Moving quickly", "Real-time environment mapping while tracking camera position without prior maps", "Noise level", "Data storage"], answer: 1, explanation: "SLAM enables AR to understand and navigate unknown environments autonomously." },
      { id: "ar_h6", question: "What does 'cloud-tethered XR' architecture provide?", options: ["Storage only", "Offloading compute to cloud servers reducing headset processing burden", "Network synchronization", "Data backup"], answer: 1, explanation: "Cloud-tethering enables lighter, cheaper XR devices through remote rendering." },
      { id: "ar_h7", question: "What is 'social XR' or 'metaverse' computing?", options: ["Social media platforms", "Persistent shared virtual worlds enabling simultaneous multi-user presence and interaction", "Video conferencing", "Online gaming only"], answer: 1, explanation: "Social XR creates collaborative virtual spaces with shared presence and persistence." }
    ]
  }
};

// Quantum Computing expansion
const QUANTUM_QUESTIONS = {
  "Quantum Computing": {
    "easy": [
      { id: "qnt_e1", question: "What fundamental unit replaces binary bits in Quantum Computing?", options: ["Qubit (Quantum Bit)", "Qbyte", "Vector Bit", "Super Bit"], answer: 0, explanation: "Qubits are the basic units of quantum information." },
      { id: "qnt_e2", question: "What quantum phenomenon allows a qubit to represent 0 and 1 simultaneously?", options: ["Superposition", "Entanglement", "Decoherence", "Tunneling"], answer: 0, explanation: "Superposition enables qubits to exist in linear combinations of basis states." },
      { id: "qnt_e3", question: "Which property describes interconnected quantum states across separate qubits?", options: ["Entanglement", "Interference", "Resistance", "Refraction"], answer: 0, explanation: "Entanglement links quantum states regardless of physical distance." },
      { id: "qnt_e4", question: "What is a 'quantum gate'?", options: ["Physical barrier", "Quantum operation manipulating qubit states analogous to classical logic gates", "Network firewall", "Particle accelerator"], answer: 1, explanation: "Quantum gates perform unitary transformations on qubit states." },
      { id: "qnt_e5", question: "What does 'quantum advantage' mean?", options: ["Higher cost only", "Quantum computer solving problems exponentially faster than classical computers", "Better graphics", "Faster networking"], answer: 1, explanation: "Quantum advantage demonstrates quantum superiority for specific problems." },
      { id: "qnt_e6", question: "What is quantum 'measurement'?", options: ["Recording qubit state non-destructively", "Collapsing superposition to definite 0 or 1 state through observation", "Counting qubits", "Calibration process"], answer: 1, explanation: "Measurement probabilistically collapses superposition losing quantum advantage." },
      { id: "qnt_e7", question: "What is 'quantum noise'?", options: ["Audio interference", "Environmental disturbances degrading qubit coherence and causing errors", "Thermal radiation", "Particle collision"], answer: 1, explanation: "Noise is the primary obstacle to practical quantum computing." }
    ],
    "medium": [
      { id: "qnt_m1", question: "What is Quantum Decoherence?", options: ["Compiling quantum code", "The loss of a quantum system's coherent state due to environmental noise", "Adding more qubits to a processor", "Encrypting classical bytes"], answer: 1, explanation: "Decoherence destroys fragile quantum superposition via thermal/magnetic disturbance." },
      { id: "qnt_m2", question: "What algorithm provides quadratic speedup for unstructured database searches?", options: ["Shor's Algorithm", "Grover's Algorithm", "Dijkstra's Algorithm", "Fourier Transform"], answer: 1, explanation: "Grover's algorithm searches unstructured items in O(√N) quantum steps." },
      { id: "qnt_m3", question: "What type of quantum hardware uses superconducting loops at near absolute zero?", options: ["Superconducting Transmon Qubits", "Photonic Fiber Routers", "Silicon Transistors", "Magnetic Disks"], answer: 0, explanation: "Transmon superconducting circuits operate in dilution refrigerators at millikelvin temperatures." },
      { id: "qnt_m4", question: "What is 'quantum annealing'?", options: ["Metal hardening", "Optimization technique finding near-optimal solutions via slow evolution", "Temperature control", "Quantum encryption"], answer: 1, explanation: "Quantum annealing solves combinatorial optimization problems efficiently." },
      { id: "qnt_m5", question: "What does 'NISQ' stand for in quantum computing?", options: ["Noisy Intermediate-Scale Quantum devices", "Near-term Industry Quantum", "Network Interface Scale Query", "New Integrated Sequence Query"], answer: 0, explanation: "NISQ refers to current-generation quantum computers with limited qubits and high error rates." },
      { id: "qnt_m6", question: "What is 'quantum parallelism'?", options: ["Running quantum computers in parallel", "Exploring exponential solution space simultaneously via superposition", "Sequential execution", "Distributed computing"], answer: 1, explanation: "Quantum parallelism processes many possibilities in single computation." },
      { id: "qnt_m7", question: "What is a 'quantum simulator'?", options: ["Video game", "Classical computer simulating quantum behavior for limited research", "Virtual machine", "Emulator only"], answer: 1, explanation: "Quantum simulators model quantum systems on classical or quantum hardware." }
    ],
    "hard": [
      { id: "qnt_h1", question: "Why does Shor's Algorithm threaten current RSA encryption standards?", options: ["It brute-forces AES keys instantly", "It factors large prime integers in polynomial time O((log N)³)", "It bypasses firewalls directly", "It clones private keys without access"], answer: 1, explanation: "Shor's algorithm efficiently factors primes, breaking RSA public key cryptography." },
      { id: "qnt_h2", question: "What does the No-Cloning Theorem state in quantum mechanics?", options: ["You cannot buy identical quantum computers", "It is impossible to create an identical copy of an arbitrary unknown quantum state", "Qubits cannot be destroyed", "Quantum code cannot be open-sourced"], answer: 1, explanation: "The No-Cloning Theorem prevents perfect copying of unknown quantum state vectors." },
      { id: "qnt_h3", question: "What is Quantum Error Correction (QEC) primary mechanism?", options: ["Rebooting quantum servers", "Encoding logical qubits across multiple entangled physical qubits to protect against noise", "Using software try-catch blocks", "Increasing cryogenic temperatures"], answer: 1, explanation: "QEC spreads logical information across topological physical qubit grids to catch errors." },
      { id: "qnt_h4", question: "What is the 'surface code' in quantum error correction?", options: ["Code displayed on screens", "2D topological code protecting qubits via local interactions enabling scalable QC", "Programming language", "Database structure"], answer: 1, explanation: "Surface codes are practical QEC approaches for large-scale quantum computers." },
      { id: "qnt_h5", question: "What does 'variational quantum algorithm' accomplish?", options: ["Hardware variation only", "Hybrid classical-quantum approach using parameterized circuits optimized classically", "Encryption only", "Testing framework"], answer: 1, explanation: "VQAs combine quantum and classical computation for near-term quantum advantage." },
      { id: "qnt_h6", question: "What is 'quantum entanglement swapping'?", options: ["Swapping computer memory", "Creating entanglement between previously unconnected qubit pairs", "Data exchange", "Networking protocol"], answer: 1, explanation: "Entanglement swapping extends quantum networks beyond direct connections." },
      { id: "qnt_h7", question: "What is a 'topological quantum computer'?", options: ["Geometric design only", "Using anyonic quasiparticles with inherent error protection via topology", "Network configuration", "Cloud infrastructure"], answer: 1, explanation: "Topological qubits are theoretically fault-tolerant by design." }
    ]
  }
};

console.log("Expanded domain questions loaded");
